#!/bin/bash

dir="$1"

# No directory has been provided, use current
if [ -z "$dir" ]
then
    dir="`pwd`"
fi

# Make sure directory ends with "/"
if [[ $dir != */ ]]
then
        dir="$dir/*"
else
        dir="$dir*"
fi

bold=$(tput bold)
normal=$(tput sgr0)

# Loop all sub-directories
for f in $dir
do
        # Only interested in directories
        [ -d "${f}" ] || continue

        echo -en "\033[0;35m${f}\033[0m "

        # Check if directory is a git repository
        if [ -d "$f/.git" ]
        then
                mod=0
                cd $f

		# Display branch name
		branchname=$(git branch | grep \* | cut -d ' ' -f2-)
		echo -en "(\033[0;34m$branchname\033[0m)\n"

                # Check for modified files
                if [ $(git status | grep modified -c) -ne 0 ]
                then
                        mod=1
			count=$(git status | grep modified -c)
                        echo -en "\033[0;31m"
                        echo "${bold}Modified files${normal} ($count)"
			git ls-files -m
                        echo -en "\033[0m"
                fi

		# Check for deleted files
		if [ $(git status | grep deleted -c) -ne 0 ]
		then
			mod=1
			count=$(git status | grep deleted -c)
			echo -en "\033[0;31m"
			echo "${bold}Deleted files${normal} ($count)"
			git ls-files -d
			echo -en "\033[0m"
		fi

                # Check for untracked files
                if [ $(git status | grep Untracked -c) -ne 0 ]
                then
                        mod=1
			count=$(git status | grep Untracked -c)
                        echo -en "\033[0;31m"
                        echo "${bold}Untracked files${normal} ($count)"
			git ls-files --others --exclude-standard
                        echo -en "\033[0m"
                fi

                # Check for unpushed changes
                if [ $(git status | grep 'Your branch is ahead' -c) -ne 0 ]
                then
                        mod=1
                        echo -en "\033[0;31m"
                        echo "${bold}Unpushed commit${normal}"
                        echo -en "\033[0m"
                fi

                # Check if everything is peachy keen
                if [ $mod -eq 0 ]
                then
                        echo -en "\033[0;92mNothing to commit\033[0m \o/ \n"
                fi

                cd ../
        else
                echo -en "\n\033[0;41mNot a git repository\033[0m\n"
        fi

        echo
done

